### ISSUE TITLE
您好，请问您使用的是什么配置的服务器进行训练的？完整训练一次需要多长时间呢？

### ISSUE THREAD

**Issue by hmbb123** [983632847/All-in-One#2]

**Comment by 983632847** [comment]
It takes approximately 1(or 3) day to train 300 epochs on an Ubuntu 18.04 server with three (or one) NVIDIA A6000 Ada GPUs, two Intel(R) Xeon(R) Platinum 8375C CPUs @ 2.90GHz，and 256G memory.

**Comment by hmbb123** [comment]
Thank you！
