### ISSUE TITLE
VLT算法的结果文件

### ISSUE THREAD

**Issue by xyl-507** [983632847/All-in-One#7]
作者您好！
感谢你们的杰出贡献。
请问一下图7中的对比算法 VLT 的结果文件可否分享一下? 提前谢谢！
![image](https://github.com/user-attachments/assets/80e69905-3687-4e05-99d7-44dc4f202f84)

**Comment by 983632847** [comment]
非常抱歉，最近比较忙没留意到你提的issue。VLT_TT和VLT_SCAR的结果文件可以从一下地址下载。
PS: 有问题可以邮件联系（andyzhangchunhui@gmail.com）


链接：https://pan.baidu.com/s/1p4YX55zOXLJl3jbKQvSVtQ?pwd=fltq 
提取码：fltq 

更新日期：2024-08-11-9:36 am

**Comment by xyl-507** [comment]
谢谢大佬！



---- 回复的原邮件 ----
| 发件人 | Chunhui ***@***.***> |
| 日期 | 2024年08月10日 18:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [983632847/All-in-One] VLT算法的结果文件 (Issue #7) |

非常抱歉，最近比较忙没留意到你提的issue。VLT_TT和VLT_SCAR的结果文件可以从一下地址下载。
PS: ***@***.***）

链接：https://pan.baidu.com/s/1LpxI2FYjCOWmfx7RMgYMVA?pwd=om2p
提取码：om2p

**Comment by xyl-507** [comment]
@983632847 
您好，您的VLT-TT结果文件好像上传成VLT-SCAR了，两个压缩包是得到的指标一样的
![image](https://github.com/user-attachments/assets/54314ae5-e3c3-4367-99e1-82b8590ab262)

**Comment by 983632847** [comment]
已更新

**Comment by xyl-507** [comment]
十分感谢！
